[package]
name = "krs"
description = "Simple Kafka command-line tool"
version = "0.1.1"
authors = ["Ivan Gozali <gozaliivan@gmail.com>"]
repository = "https://github.com/igozali/krs"
homepage = "https://github.com/igozali/krs"
license = "Apache-2.0"
readme = "README.md"
# documentation = "https://github.com/igozali/krs"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "~2.33.0"
kafka = "~0.8.0"
rdkafka = "~0.21.0"
dotenv = "~0.15.0"
